# Generated by Django 3.1.1 on 2020-11-19 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=50)),
                ('main_category', models.ForeignKey(blank=True, limit_choices_to={'main_category': None}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maincategory', to='posts.category')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, limit_choices_to={'main_category': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_category', to='posts.category'),
        ),
    ]
