# Generated by Django 3.1.1 on 2020-09-20 11:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeHotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Countery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('main_countery', models.ForeignKey(blank=True, limit_choices_to={'main_countery': None}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maincountery', to='Booking.countery')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('main_category', models.ForeignKey(blank=True, limit_choices_to={'main_category': None}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maincategory', to='Booking.category')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('post_slug', models.SlugField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='post/')),
                ('price', models.FloatField(default=True)),
                ('active', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, limit_choices_to={'main_category': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_category', to='Booking.category')),
                ('countery', models.ForeignKey(blank=True, limit_choices_to={'main_countery': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_countery', to='Booking.countery')),
                ('typehotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TypeHotel', to='Booking.typehotel')),
            ],
        ),
        migrations.CreateModel(
            name='AdImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Booking_images/')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_images', to='Booking.booking')),
            ],
        ),
    ]
