# Generated by Django 3.1.1 on 2020-09-20 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeHotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Countery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('main_countery', models.ForeignKey(blank=True, limit_choices_to={'main_countery': None}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maincountery', to='Booking.countery')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('main_category', models.ForeignKey(blank=True, limit_choices_to={'main_category': None}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maincategory', to='Booking.category')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('room', models.CharField(choices=[('Single Room', 'Single Room'), ('Single Room', 'Single Room'), ('Double Room', 'Double Room'), ('VIP Single Room', 'VIP Single Room'), ('VIP Double Room', 'VIP Double Room')], max_length=100, null=True)),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('post_slug', models.SlugField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='post/')),
                ('price', models.FloatField(default=True)),
                ('active', models.BooleanField(default=False)),
                ('condition', models.CharField(blank=True, choices=[('Good', 'Good'), ('Very Good', 'Very Good'), ('Good', 'Good'), ('Very Good', 'Very Good')], max_length=15, null=True)),
                ('status_room', models.CharField(blank=True, choices=[('booked up', 'booked up'), ('Available', 'Available')], max_length=15, null=True)),
                ('category', models.ForeignKey(blank=True, limit_choices_to={'main_category': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_category', to='Booking.category')),
                ('countery', models.ForeignKey(blank=True, limit_choices_to={'main_countery': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_countery', to='Booking.countery')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_owner', to=settings.AUTH_USER_MODEL)),
                ('typehotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TypeHotel', to='Booking.typehotel')),
            ],
        ),
        migrations.CreateModel(
            name='AdImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Booking_images/')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_images', to='Booking.booking')),
            ],
        ),
    ]
